name: Test Dockerfile

on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  build-cuda:

    runs-on: [cuda]

    steps:
      - uses: actions/checkout@v2

      - name: Delete previous containers.
        run: docker rmi blade || true

      - name: Build the Docker image.
        run: docker build . --no-cache --file Dockerfile --tag blade:latest

      - name: Run Python build test.
        run: docker run --gpus all --rm blade bash -c "cd blade && pip install -v . && python3 -c 'import blade'"

      - name: Run ninja test.
        run: docker run --gpus all --rm blade bash -c "cd blade/build && ninja test"

      - name: Run memory benchmark.
        run: |
          docker run --gpus all -v $(pwd):/tmp --rm blade bash -c \
          "cd blade/build && ./benchmarks/memory/benchmark-memory --benchmark_format=json | tee /tmp/benchmark_result.json"

      - name: Store memory benchmark.
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Memory Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          comment-on-alert: true
          alert-comment-cc-users: '@luigifcruz'
          auto-push: true

      - name: Run modules benchmark.
        run: |
          docker run --gpus all -v $(pwd):/tmp --rm blade bash -c \
          "cd blade/build && ./benchmarks/modules/benchmark-modules --benchmark_format=json | tee /tmp/benchmark_result.json"

      - name: Store modules benchmark.
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Modules Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          comment-on-alert: true
          alert-comment-cc-users: '@luigifcruz'
          auto-push: true

      - name: Run Bundles benchmark.
        run: |
          docker run --gpus all -v $(pwd):/tmp --rm blade bash -c \
          "cd blade/build && ./benchmarks/bundles/benchmark-bundles --benchmark_format=json | tee /tmp/benchmark_result.json"

      - name: Store bundles benchmark.
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Bundles Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          comment-on-alert: true
          alert-comment-cc-users: '@luigifcruz'
          auto-push: true
