name: Test Dockerfile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-cuda:

    runs-on: [cuda]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete previous containers.
        run: docker rmi blade || true

      - name: Build the Docker image.
        run: docker build . --no-cache --file Dockerfile --tag blade:latest

      - name: Run Python build test.
        run: docker run --gpus all --rm blade bash -c "cd blade && pip install -v . && python3 -c 'import blade'"

      - name: Run ninja test.
        run: docker run --gpus all --rm blade bash -c "cd blade/build && ninja test"
